### ISSUE TITLE
Errors building on Fedora 40

### ISSUE THREAD

**Issue by jasaldivara** [rhx/SwiftGLib#8]
I just updated my system to Fedora 40 (On ARM64 architecture)

On my project based on SwiftGtk (Gtk 3), I deleted the `.build` directory and the `Package.resolved` file.

Then I ran `swift build`, but there are some error messages, and the package is not built:

```
Building for debugging...
/home/lalo/codigos/chickenpos/.build/plugins/outputs/swiftglib/GLib/gir2swift-plugin/gir2swift-generated/GLib/GLib-2.0-functions.swift:6285:18: error: 'g_open' is unavailable: Variadic function is unavailable
    let result = g_open(filename, gint(flags), gint(mode))
                 ^~~~~~
CGLib.g_open:2:13: note: 'g_open' has been explicitly marked unavailable here
public func g_open(_: UnsafePointer<CChar>, _: Int32, _ varargs: Any...) -> Int32
            ^
/home/lalo/codigos/chickenpos/.build/plugins/outputs/swiftglib/GLib/gir2swift-plugin/gir2swift-generated/GLib/GLib-2.0-functions.swift:7620:18: error: cannot find 'g_set_prgname_once' in scope
    let result = g_set_prgname_once(prgname)
                 ^~~~~~~~~~~~~~~~~~
error: emit-module command failed with exit code 1 (use -v to see invocation)
/home/lalo/codigos/chickenpos/.build/plugins/outputs/swiftglib/GLib/gir2swift-plugin/gir2swift-generated/GLib/GLib-2.0-functions.swift:6285:18: error: 'g_open' is unavailable: Variadic function is unavailable
    let result = g_open(filename, gint(flags), gint(mode))
                 ^~~~~~
CGLib.g_open:2:13: note: 'g_open' has been explicitly marked unavailable here
public func g_open(_: UnsafePointer<CChar>, _: Int32, _ varargs: Any...) -> Int32
            ^
/home/lalo/codigos/chickenpos/.build/plugins/outputs/swiftglib/GLib/gir2swift-plugin/gir2swift-generated/GLib/GLib-2.0-functions.swift:7620:18: error: cannot find 'g_set_prgname_once' in scope
    let result = g_set_prgname_once(prgname)
                 ^~~~~~~~~~~~~~~~~~
```

**Comment by rhx** [comment]
Can you try the following, then try again and let me know if you still get the error:
```sh
swift package purge-cache
swift package update
rm -rf .build Package.resolved
```

**Comment by jasaldivara** [comment]
Yes, the errors persisted after running those commands

**Comment by rhx** [comment]
Thanks.  I have committed a fix now (if you could double-check and let me know, that'd be great).  Don't forget to run
```sh
swift package purge-cache
swift package update
rm -rf .build Package.resolved
```
to make sure you pull in the updated version of SwiftGLib.

**Comment by jasaldivara** [comment]
Now it builds without problems. No more error messages.

Thanks

**Comment by jasaldivara** [comment]
Reopening because the error is still present on x86_64 (Fedora 40)

The same error messages:

```
/home/lalo/codigos/chickenpos/.build/plugins/outputs/swiftglib/GLib/gir2swift-plugin/gir2swift-generated/GLib/GLib-2.0-functions.swift:6285:18: error: 'g_open' is unavailable: Variadic function is unavailable
    let result = g_open(filename, gint(flags), gint(mode))
                 ^~~~~~
CGLib.g_open:2:13: note: 'g_open' has been explicitly marked unavailable here
public func g_open(_: UnsafePointer<CChar>, _: Int32, _ varargs: Any...) -> Int32
            ^
...
```

It works fine on aarch64, but the error persist on x86_64 CPU (Intel Core i5)

**Comment by rhx** [comment]
Can you double-check, please?  I have pulled your changes and made some updates to make this compile again under macOS.  Ubuntu builds seem to work fine, but if you could check with that this fixes your issues in Fedora, that'd be great!

**Comment by jasaldivara** [comment]
Building and  running my project based on SwiftGtk now works fine.

Also, building SwiftGlib with `swift build` works fine on Fedora 40 x86_64, but testing SwiftGlib with `swift test` (inside SwiftGlib directory) fails with an error message on the testDirOpen test case:

```
SwiftGLib $ swift test

Building for debugging...
[4/4] Compiling plugin gir2swift-plugin
Build complete! (0.14s)
Test Suite 'All tests' started at 2024-06-04 22:31:28.478
Test Suite 'debug.xctest' started at 2024-06-04 22:31:28.479
Test Suite 'GLibTests' started at 2024-06-04 22:31:28.479
Test Case 'GLibTests.testArray' started at 2024-06-04 22:31:28.479
Test Case 'GLibTests.testArray' passed (0.001 seconds)
Test Case 'GLibTests.testByteArray' started at 2024-06-04 22:31:28.480
Test Case 'GLibTests.testByteArray' passed (0.101 seconds)
Test Case 'GLibTests.testByteArrayString' started at 2024-06-04 22:31:28.581
Test Case 'GLibTests.testByteArrayString' passed (0.0 seconds)
Test Case 'GLibTests.testDateTime' started at 2024-06-04 22:31:28.581
Test Case 'GLibTests.testDateTime' passed (0.0 seconds)
Test Case 'GLibTests.testDateTimeUnixUTC' started at 2024-06-04 22:31:28.582
Test Case 'GLibTests.testDateTimeUnixUTC' passed (0.0 seconds)
Test Case 'GLibTests.testDefaultMainContext' started at 2024-06-04 22:31:28.582
Test Case 'GLibTests.testDefaultMainContext' passed (0.0 seconds)
Test Case 'GLibTests.testDirOpen' started at 2024-06-04 22:31:28.582
malloc(): unaligned tcache chunk detected
error: Exited with signal code 6
```

I think is the same error that was present on macOS?

If I remove the `dir.close()` line from testDirOpen, now that test case passes, but another case fails:
```
    /// check that we can read a directory
    func testDirOpen() {
        let existing_path = "/tmp"
        do {
            guard let dir = try Dir.open(path: existing_path, flags: 0) else {
                XCTFail() ; return
            }
            let first: String? = dir.readName()    // get the first entry
            XCTAssertNotNil(first)
            guard let first = first else { return }
            XCTAssertFalse(first.isEmpty)
            dir.rewind()                            // go back
            let first_again = dir.readName()       // get first entry again
            XCTAssertEqual(first, first_again)
        } catch {
            XCTFail("\(error)")
        }
    }
```

```
Building for debugging...
warning: direct reference to protected function `$sSJ12isWhitespaceSbvg' in `/usr/libexec/swift/5.8.1/bin/../lib/swift/linux/libswiftCore.so' may break pointer equality
warning: direct reference to protected function `$sSJ12isWhitespaceSbvg' in `/usr/libexec/swift/5.8.1/bin/../lib/swift/linux/libswiftCore.so' may break pointer equality
[8/8] Compiling GLibTests GLibTests.swift
Build complete! (1.08s)
Test Suite 'All tests' started at 2024-06-04 22:40:24.997
Test Suite 'debug.xctest' started at 2024-06-04 22:40:24.999
Test Suite 'GLibTests' started at 2024-06-04 22:40:24.999
Test Case 'GLibTests.testArray' started at 2024-06-04 22:40:24.999
Test Case 'GLibTests.testArray' passed (0.002 seconds)
Test Case 'GLibTests.testByteArray' started at 2024-06-04 22:40:25.002
Test Case 'GLibTests.testByteArray' passed (0.0 seconds)
Test Case 'GLibTests.testByteArrayString' started at 2024-06-04 22:40:25.002
Test Case 'GLibTests.testByteArrayString' passed (0.0 seconds)
Test Case 'GLibTests.testDateTime' started at 2024-06-04 22:40:25.003
Test Case 'GLibTests.testDateTime' passed (0.0 seconds)
Test Case 'GLibTests.testDateTimeUnixUTC' started at 2024-06-04 22:40:25.003
Test Case 'GLibTests.testDateTimeUnixUTC' passed (0.0 seconds)
Test Case 'GLibTests.testDefaultMainContext' started at 2024-06-04 22:40:25.003
Test Case 'GLibTests.testDefaultMainContext' passed (0.0 seconds)
Test Case 'GLibTests.testDirOpen' started at 2024-06-04 22:40:25.003
Test Case 'GLibTests.testDirOpen' passed (0.0 seconds)
Test Case 'GLibTests.testDoubleIEEE754' started at 2024-06-04 22:40:25.004
Test Case 'GLibTests.testDoubleIEEE754' passed (0.0 seconds)
Test Case 'GLibTests.testErrorType' started at 2024-06-04 22:40:25.004
Test Case 'GLibTests.testErrorType' passed (0.0 seconds)
Test Case 'GLibTests.testFloatIEEE754' started at 2024-06-04 22:40:25.004
Test Case 'GLibTests.testFloatIEEE754' passed (0.0 seconds)
Test Case 'GLibTests.testLog' started at 2024-06-04 22:40:25.004
Test Case 'GLibTests.testLog' passed (0.0 seconds)
Test Case 'GLibTests.testLogDomain' started at 2024-06-04 22:40:25.005
error: Exited with signal code 5
```

**Comment by rhx** [comment]
Thanks, this is fixed now: the crash was caused by an unbalanced  `unref()` in `Dir.deinit`.

**Comment by jasaldivara** [comment]
This problem is present again on Fedora 43 x86_64

```
.build/plugins/outputs/swiftglib/GLib/destination/gir2swift-plugin/gir2swift-generated/GLib/GLib-2.0-functions.swift:6493:18: error: 'g_open' is unavailable: Variadic function is unavailable
 6491 | /// See your C library manual for more details about `open()`.
 6492 | @inlinable public func open(filename: UnsafePointer<gchar>!, flags: Int, mode: Int) -> Int {
 6493 |     let result = g_open(filename, gint(flags), gint(mode))
      |                  `- error: 'g_open' is unavailable: Variadic function is unavailable
 6494 |     let rv = Int(result)
 6495 |     return rv

.build/checkouts/SwiftGLib/Sources/CGLib/glib_bridging.h:8:12: note: 'g_open' has been explicitly marked unavailable here
  6 | #define g_open g_open_orig
  7 | #else
  8 | extern int g_open(const char *, int, ...) __nonnull ((1));
    |            `- note: 'g_open' has been explicitly marked unavailable here
  9 | #endif
 10 | #endif

```
I'm not sure why `g_open` is declared as variadic when the [documentation](https://docs.gtk.org/glib/func.open.html) says it has a signature `int g_open (const gchar*, int, int)`

**Comment by rhx** [comment]
This appears to be a silly one, that's caused a lot of head-scratching: it looks like this was fixed on the development branch all along (that's why I couldn't reproduce it), but was never merged into 'main'.  @jasaldivara if you get a chance, could you do a
```
swift package purge-cache
swift package update
rm -rf .build Package.resolved
```
and check that this works for you now?

**Comment by jasaldivara** [comment]
Yes, I can confirm this is working fine now on Fedora (both x86_64 and aarch64).

Also, I think this is the same bug as: https://github.com/rhx/SwiftHelloGtk/issues/13

**Comment by rhx** [comment]
Yes, this was actually also an issue in the SwiftGtk monorepo -- all fixed now.
